POST http://localhost:8090/residents/1/relationship HTTP/1.1
Content-Type: application/json

{
    "familySerialNumber": 2,
    "relationShip": "child"
}

####

PUT http://localhost:8090/residents/1/relationship/2 HTTP/1.1
Content-Type: application/json

{
    "relationShip": "child"
}

####

DELETE http://localhost:8090/residents/1/relationship/2 HTTP/1.1