POST http://localhost:8090/household HTTP/1.1
Content-Type: application/json

{
  "houseHolder": 2,
  "reason": "전입",
  "nowAddress": "경상남도 김해시 김해대로 2326"
}

####

DELETE http://localhost:8090/household/4 HTTP/1.1

####

POST http://localhost:8090/household/3/movement HTTP/1.1
Content-Type: application/json

{
  "address": "경상남도 김해시 김해대로 2326",
  "isFinal": "Y"
}

####

PUT http://localhost:8090/household/3/movement/20220530 HTTP/1.1
Content-Type: application/json

{
"address": "부산진구 유명가수 일취월장하며 성장 중",
"isFinal": "Y"
}

####

DELETE http://localhost:8090/household/3/movement/20220530 HTTP/1.1